In [4]:
import numpy as np
#Q1.
arr=np.array([2,4,3,5,8,9])
mask = arr>5
filter = arr[mask]
print(filter)

[8 9]


In [5]:
#Q2.
arr2 = np.array([11,12,13,14,15,16,17,18,19,20,21,23])
mask2 = (arr2 % 2 == 0)
arr2[mask2] = -1
print(arr2)

[11 -1 13 -1 15 -1 17 -1 19 -1 21 23]


In [7]:
#Q3.
arr3 = np.random.randint(40,98,size=(5,3))
print(f"The mean of the students marks are: {np.mean(arr3,axis=1)}")
print(f"The max of all students is: {np.max(arr3,axis=1)}")
min_global_arr3 = np.min(arr3)
max_global_arr3 = np.max(arr3)

normalized_arr3_global_min_max = (arr3 - min_global_arr3) / (max_global_arr3 - min_global_arr3)
print(f"The normalized score of the marks are: {normalized_arr3_global_min_max}")

The mean of the students marks are: [89.66666667 62.33333333 82.66666667 78.33333333 69.        ]
The max of all students is: [95 74 97 95 93]
The normalized score of the marks are: [[0.96 0.82 0.78]
 [0.26 0.54 0.12]
 [0.46 1.   0.68]
 [0.22 0.96 0.7 ]
 [0.92 0.   0.4 ]]
