In [7]:
import numpy as np
a = np.array([[2,3,5],[3,12,4],[329,23,54]])
b = np.array([[6,7,8],[324,6545,234],[345,234,665]])
print(a)

[[  2   3   5]
 [  3  12   4]
 [329  23  54]]


In [8]:
a.ndim
a.shape
a.size

9

In [9]:
d = np.array([11,22,33,44,55,66,77,88,99,10])
print(np.mean(d))
print(np.sum(d))
print(f"The max value is: {np.max(d)}")
print(f"The min value is: {np.min(d)}")
print(d)

50.5
505
The max value is: 99
The min value is: 10
[11 22 33 44 55 66 77 88 99 10]


In [10]:
r = np.random.randint(1,100,size=(50,5))
print(f"The median of the 2d array is: {np.median(r)}")
print(f"The mean of the 2d arrays is: {np.mean(r)}")
print(f"The std deviatiobn of 2d arryas: {np.std(r)}")
# print(r)

The median of the 2d array is: 53.0
The mean of the 2d arrays is: 52.832
The std deviatiobn of 2d arryas: 27.101065956895496
