In [6]:
#importing libraries
import numpy as np

In [7]:
#Q1. Generate a 4x4 identity matrix using NumPy.
a = np.random.randint(1,100,size=(4,4))
print(a)

[[39 23 42 15]
 [68 66  2 50]
 [ 7 49 42 15]
 [51 23 48 29]]


In [8]:
#Q2. Create a 1D array of 100 random numbers between 1 and 1000. Find the maximum, minimum, and mean of the array.
b = np.random.randint(1,1000,size=(1,100))
print(b)

[[759 276 142  87 413  98 997 440 128 923 195 679 647  71  84 706 249 226
  205 896 762 182 930 999 279  38  37 988 926 516 647 721 840 960 135 316
  681 524 670 672 203 442 562 882 509 317 186 157 716 688 760 112 644 641
   95 808 699 377 629 273 963 685 796 239 204 694 923 114 541 996 621 978
  118 329 298 773 797 235 571 536 919 727 408 186 621 690 391 538 440 857
  910 598 892 946 753  47 306 170 988 972]]


In [9]:
#Q3. Create a 6x6 matrix with random integers from 1 to 100. Find and print all elements greater than 50.
matrix = np.random.randint(1, 101, size=(6, 6))
print("Generated Matrix:\n", matrix)

print("\nElements greater than 50:")
for row in matrix:
    for element in row:
        if element > 50:
            print(element)

Generated Matrix:
 [[91 36 23 32 94 89]
 [ 3 62 87 85 91 50]
 [78 39 92  9 34  1]
 [21 11 39 64 64  1]
 [53 46 64 16 97 22]
 [94 95 11 83 85 24]]

Elements greater than 50:
91
94
89
62
87
85
91
78
92
64
64
53
64
97
94
95
83
85


In [10]:
#Q4. Create a 1D array of 20 elements and split it into 4 equal parts.
original_array = np.random.randint(0, 10, 20)
print("Original Array:", original_array)

# Split the array into 4 equal parts
split_array = np.split(original_array, 4)

print("\nSplit Array into 4 Equal Parts:")
for i, part in enumerate(split_array):
    print(f"Part {i+1}:", part)

Original Array: [0 0 0 8 7 7 5 5 8 4 4 1 0 9 8 3 5 9 4 4]

Split Array into 4 Equal Parts:
Part 1: [0 0 0 8 7]
Part 2: [7 5 5 8 4]
Part 3: [4 1 0 9 8]
Part 4: [3 5 9 4 4]


In [11]:
#Q5. Given a 2D matrix, write code to calculate the mean of each row and each column.
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("Original Matrix:\n", matrix)

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1)
print("\nMean of each row:", row_means)

# Calculate the mean of each column
column_means = np.mean(matrix, axis=0)
print("Mean of each column:", column_means)

Original Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Mean of each row: [ 2.5  6.5 10.5]
Mean of each column: [5. 6. 7. 8.]


In [12]:
"""Case Study 1: Analyzing Student Scores
Scenario:
You are provided with scores of 10 students in 5 subjects. Each row represents a student and
each column represents a subject.
Tasks:
1. Print the average score of each student.
2. Print the average score of each subject.
3. Find the student with the highest average score.
4. Find the subject in which students performed the best on average.
5. Normalize the scores between 0 and 1."""

# Student scores data (10 students, 5 subjects)
student_scores = np.array([[85, 90, 78, 92, 88],
                           [76, 82, 95, 88, 79],
                           [91, 87, 80, 85, 94],
                           [68, 75, 86, 90, 82],
                           [93, 79, 88, 76, 85],
                           [80, 88, 92, 84, 77],
                           [72, 85, 79, 91, 89],
                           [88, 92, 83, 78, 96],
                           [79, 81, 87, 94, 80],
                           [95, 86, 75, 82, 91]])

# 1. Print the average score of each student
average_student_scores = np.mean(student_scores, axis=1)
print("Average score of each student:", average_student_scores)

# 2. Print the average score of each subject
average_subject_scores = np.mean(student_scores, axis=0)
print("\nAverage score of each subject:", average_subject_scores)

# 3. Find the student with the highest average score
highest_average_score = np.max(average_student_scores)
student_index_highest_average = np.argmax(average_student_scores)
print(f"\nStudent with the highest average score (Index {student_index_highest_average}): {highest_average_score:.2f}")

# 4. Find the subject in which students performed the best on average
highest_average_subject_score = np.max(average_subject_scores)
subject_index_highest_average = np.argmax(average_subject_scores)
print(f"\nSubject with the highest average score (Index {subject_index_highest_average}): {highest_average_subject_score:.2f}")

# 5. Normalize the scores between 0 and 1
min_score = np.min(student_scores)
max_score = np.max(student_scores)
normalized_scores = (student_scores - min_score) / (max_score - min_score)
print("\nNormalized scores between 0 and 1:\n", normalized_scores)

Average score of each student: [86.6 84.  87.4 80.2 84.2 84.2 83.2 87.4 84.2 85.8]

Average score of each subject: [82.7 84.5 84.3 86.  86.1]

Student with the highest average score (Index 2): 87.40

Subject with the highest average score (Index 4): 86.10

Normalized scores between 0 and 1:
 [[0.60714286 0.78571429 0.35714286 0.85714286 0.71428571]
 [0.28571429 0.5        0.96428571 0.71428571 0.39285714]
 [0.82142857 0.67857143 0.42857143 0.60714286 0.92857143]
 [0.         0.25       0.64285714 0.78571429 0.5       ]
 [0.89285714 0.39285714 0.71428571 0.28571429 0.60714286]
 [0.42857143 0.71428571 0.85714286 0.57142857 0.32142857]
 [0.14285714 0.60714286 0.39285714 0.82142857 0.75      ]
 [0.71428571 0.85714286 0.53571429 0.35714286 1.        ]
 [0.39285714 0.46428571 0.67857143 0.92857143 0.42857143]
 [0.96428571 0.64285714 0.25       0.5        0.82142857]]


In [13]:
"""Case Study 2: Sales Data Analysis
Scenario:
You are given monthly sales data (in lakhs) for 4 products (A, B, C, D) over 6 months. Perform
analysis using NumPy.
Tasks:
1. Calculate the total sales for each product.
2. Calculate the total sales for each month.
3. Identify the month in which sales were the highest for Product B.
4. Calculate the average monthly sales of each product.
5. Calculate the percentage increase in sales of Product A from the first to the last month.
6. Find the product with the highest overall sales."""

sales_data = np.array([[30, 45, 25, 50],    # Month 1 (A, B, C, D)
                       [35, 40, 30, 55],    # Month 2
                       [40, 52, 28, 60],    # Month 3
                       [48, 48, 35, 58],    # Month 4
                       [42, 55, 32, 62],    # Month 5
                       [50, 60, 40, 65]])    # Month 6

products = ['A', 'B', 'C', 'D']
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

# 1. Calculate the total sales for each product
total_sales_per_product = np.sum(sales_data, axis=0)
print("Total sales for each product:")
for i, total in enumerate(total_sales_per_product):
    print(f"Product {products[i]}: {total} lakhs")

# 2. Calculate the total sales for each month
total_sales_per_month = np.sum(sales_data, axis=1)
print("\nTotal sales for each month:")
for i, total in enumerate(total_sales_per_month):
    print(f"{months[i]}: {total} lakhs")

# 3. Identify the month in which sales were the highest for Product B
product_b_sales = sales_data[:, 1]  # Sales of Product B (second column)
month_highest_sales_b_index = np.argmax(product_b_sales)
month_highest_sales_b = months[month_highest_sales_b_index]
highest_sales_b = product_b_sales[month_highest_sales_b_index]
print(f"\nMonth with the highest sales for Product B: {month_highest_sales_b} ({highest_sales_b} lakhs)")

# 4. Calculate the average monthly sales of each product
average_monthly_sales_per_product = np.mean(sales_data, axis=0)
print("\nAverage monthly sales of each product:")
for i, average in enumerate(average_monthly_sales_per_product):
    print(f"Product {products[i]}: {average:.2f} lakhs")

# 5. Calculate the percentage increase in sales of Product A from the first to the last month
product_a_sales_first_month = sales_data[0, 0]
product_a_sales_last_month = sales_data[-1, 0]
percentage_increase_a = ((product_a_sales_last_month - product_a_sales_first_month) / product_a_sales_first_month) * 100
print(f"\nPercentage increase in sales of Product A from {months[0]} to {months[-1]}: {percentage_increase_a:.2f}%")

# 6. Find the product with the highest overall sales
highest_overall_sales = np.max(total_sales_per_product)
product_index_highest_overall_sales = np.argmax(total_sales_per_product)
product_highest_overall_sales = products[product_index_highest_overall_sales]
print(f"\nProduct with the highest overall sales: {product_highest_overall_sales} ({highest_overall_sales} lakhs)")

Total sales for each product:
Product A: 245 lakhs
Product B: 300 lakhs
Product C: 190 lakhs
Product D: 350 lakhs

Total sales for each month:
Jan: 150 lakhs
Feb: 160 lakhs
Mar: 180 lakhs
Apr: 189 lakhs
May: 191 lakhs
Jun: 215 lakhs

Month with the highest sales for Product B: Jun (60 lakhs)

Average monthly sales of each product:
Product A: 40.83 lakhs
Product B: 50.00 lakhs
Product C: 31.67 lakhs
Product D: 58.33 lakhs

Percentage increase in sales of Product A from Jan to Jun: 66.67%

Product with the highest overall sales: D (350 lakhs)
